#45, add registration page for pacient
io2-2022-JKL/team_L_frontend pull request #3
Opened 2022-03-26 15:15 UTC by MaksMatch

2022-03-26 22:01 UTC, kar-now commented on src/pages/pacient/login/LoginPacient.js
> +import LoginForm from "../../../forms/LoginForm";
why is it changed?

2022-03-26 22:02 UTC, kar-now commented on src/pages/pacient/login/LoginPacient.js
> +import LoginForm from "../../../forms/LoginForm";
"Forms" is the correct folder( not "forms")

2022-03-26 22:03 UTC, kar-now commented on src/pages/pacient/registration/RegistrationPacient.js
> +import RegistrationPacientForm from "../../../forms/RegistrationPacientForm";
change "forms" - > "Forms"

2022-03-26 22:04 UTC, kar-now commented on src/pages/doctor/login/LoginDoctor.js
> -import LoginForm from "../../../Forms/LoginForm";
change "forms" - > "Forms"

2022-03-26 22:06 UTC, kar-now requested changes
wrong forms imports (folder is calles "Forms" and not "forms")

2022-03-27 19:32 UTC, MaksMatch commented
fixed

2022-03-27 19:33 UTC, kar-now approved these changes

2022-03-27 19:46 UTC, merged